In [15]:
import torch
import numpy as np

# Create a 2-D tensor from a list
M = np.array([[0,1,1,0], 
                  [0,0,0,1],
                  [1,0,0,0],
                  [0,1,0,0]])


In [22]:
M

array([[0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [17]:
Q = M @ M @ M

In [23]:
M @ M

array([[1, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1]])

In [19]:
Q

array([[0, 2, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 0, 0]])